### PR TITLE
Add RHEL 8

### PR DESCRIPTION
**Pull request by roniezr**

### CODE REVIEW

**Review by kobihk — APPROVED** [review]

**Comment by roniezr** [comment]
@goozbach could you please review?

**Comment by jirimacku** [comment]
+1

**Comment by roniezr** [comment]
@goozbach could you please review?

**Review by goozbach — APPROVED** [review]

**Comment by roniezr** [comment]
@goozbach Hi, I see ansible-galaxy is still not updated, can you please update ansible-galaxy as well?

**Pull request merged**
